[package]
name = "paw-kafka-topic-backup"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
axum = "0.8.4"
prometheus = "0.14.0"
log4rs = "1.4.0"
log = "0.4.28"
sqlx = {  version = "0.8.6", features = ["postgres", "runtime-tokio", "tls-rustls", "macros", "chrono"] }
rdkafka = { version = "0.38.0", features = ["tracing", "tokio", "ssl-vendored"] }
serde_json = "1.0"
base64 = "0.22.1"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
# OpenTelemetry dependencies
opentelemetry = "0.26.0"
opentelemetry_sdk = { version = "0.26.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.26.0", features = ["grpc-tonic"] }
tracing = "0.1"
tracing-opentelemetry = "0.27.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
testcontainers = "0.16"
testcontainers-modules = { version = "0.4", features = ["postgres"] }


