apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: paw-kafka-topic-backup
  namespace: paw
  labels:
    team: paw
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 0
    max: 0
  env:
    - name: PGSSLMODE
      value: "VerifyFull"
    - name: PGSSLROOTCERT
      value: "$(NAIS_DATABASE_PAW_KAFKA_TOPIC_BACKUP_TOPICBACKUP_SSLROOTCERT)"
    - name: PGSSLCERT
      value: "$(NAIS_DATABASE_PAW_KAFKA_TOPIC_BACKUP_TOPICBACKUP_SSLCERT)"
    - name: PGSSLKEY
      value: "$(NAIS_DATABASE_PAW_KAFKA_TOPIC_BACKUP_TOPICBACKUP_SSLKEY)"
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  startup:
    failureThreshold: 10
    initialDelay: 2
    path: /internal/hasStarted
    periodSeconds: 10
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/metrics
  kafka:
    pool: {{ kafka }}
  resources:
    limits:
      memory: 32Mi
    requests:
      memory: 32Mi
      cpu: 20m
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-custom-1-3840
        databases:
          - name: topicbackuphdd
        diskType: HDD
        highAvailability: false
        pointInTimeRecovery: false
        diskAutoresize: true
        insights:
          enabled: false
